<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>fece7b0d-286b-494a-801c-fa2c80284ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.delete-confirm.popActionButtons.popupConfirmButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='eformrender-page']/body/div[5]/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Yes' or . = 'Yes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b3af14f-cd8a-4a03-b982-26cee7d81c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete-confirm popActionButtons popupConfirmButton</value>
      <webElementGuid>6893415c-8a3c-4a97-907e-b1586c43df29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>0cb2d177-4342-48b2-b486-077efe1a820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eformrender-page&quot;)/body[1]/div[@class=&quot;k-widget k-window&quot;]/div[@class=&quot;confirmWindowWrapper k-window-content k-content&quot;]/div[@class=&quot;confirmationButtonWrapper&quot;]/button[@class=&quot;delete-confirm popActionButtons popupConfirmButton&quot;]</value>
      <webElementGuid>6a17aacb-fb4a-42a7-8d84-1324581ecdf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='eformrender-page']/body/div[5]/div[2]/div[2]/button</value>
      <webElementGuid>ae90140b-487e-4c6e-a248-83db1276dafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::button[1]</value>
      <webElementGuid>76ff4d4e-d2b5-4b06-9802-6139f92699df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::button[1]</value>
      <webElementGuid>4e0b8f12-bb5c-4a4d-86fa-6f49f7f1999d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>2edfb1a0-1f93-4d39-81ab-ce2353a84305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>95936eb9-35c8-4636-b3d6-ff4a48a07e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>587259c2-8d3a-4c52-b4fb-a9399f733366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>57be730b-3577-4d12-85e2-5591c321a391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='eformrender-page']/body/div[6]/div[2]/div[2]/button</value>
      <webElementGuid>a3365372-9353-4338-a5b1-167293407702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::button[1]</value>
      <webElementGuid>fc64409c-9ced-4e96-bb55-4a0daaeb68c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
