<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>30ff07bd-28af-4019-afbb-f411c3675e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.delete-confirm.save-confirm.popActionButtons.popupConfirmButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='eformrender-page']/body/div[6]/div[2]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5142269f-0b62-4d90-89d3-9bd91653b1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete-confirm save-confirm popActionButtons popupConfirmButton</value>
      <webElementGuid>b9d7da6d-57ca-419b-80ab-690ef155d27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>4b82177a-5277-4300-bef5-aa1324531162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eformrender-page&quot;)/body[1]/div[@class=&quot;k-widget k-window&quot;]/div[@class=&quot;confirmWindowWrapper saveas k-window-content k-content&quot;]/div[@class=&quot;confirmationButtonWrapper&quot;]/button[@class=&quot;delete-confirm save-confirm popActionButtons popupConfirmButton&quot;]</value>
      <webElementGuid>ce298f99-b227-4093-a740-ebbdffa4a80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='eformrender-page']/body/div[6]/div[2]/div[2]/button</value>
      <webElementGuid>9289279c-493c-4f9f-862d-f06c49ddf48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a title to use as a label for this draft.'])[1]/following::button[1]</value>
      <webElementGuid>ec61f7c2-0727-4713-9eb3-4cd70f7b1cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>ef0f0afa-b2c4-4d46-8506-ea9be094a1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>1326a964-fe2f-4338-8e25-68ca5919d1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>d25e78e2-abfe-4c1d-b7ad-9b6a0f7716dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>cac1910d-b894-4d80-990f-ce663811d0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>d95d4784-f56b-4145-9f41-d1fe45f2f5f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
