<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>container</name>
   <tag></tag>
   <elementGuidId>8230174f-565d-415d-99c5-5c03372e10ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>f3ce0e35-5609-4329-9706-7b913d074a11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
