<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Preview  Submission</name>
   <tag></tag>
   <elementGuidId>0930fee1-3954-4f1a-ad2b-8fc2c69554ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Preview &amp; Submission&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='Preview &amp; Submission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d444b2b-5ec5-40bd-82c4-330626afe943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>e32851b7-4e27-4565-a192-e67cb422511d</value>
      <webElementGuid>4cfdb686-959b-41e4-abcd-cf1655b8b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSectionProgressBarCell active</value>
      <webElementGuid>9d067389-47d9-4ede-a0c4-91936ef8d25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>258354db-1eec-418d-90c3-e8c53490932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>98a5979e-9f6f-49c3-b0e3-753c7e1d5541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Preview &amp; Submission</value>
      <webElementGuid>6282e45d-abe7-4d61-acf1-6848377ee557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Preview &amp; Submission</value>
      <webElementGuid>776ae06c-8c2b-412d-9f49-168a779bf683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8905a0d8-331b-4521-921e-b0403944fb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>67f83255-bc5f-4d69-9915-9e1938250136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview &amp; Submission</value>
      <webElementGuid>cd2e590f-14c9-469f-b04c-872eb6d7b1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionTabs&quot;)/div[@class=&quot;formSectionProgressBarCell active&quot;]</value>
      <webElementGuid>4abf7216-4ef2-4c5d-ba28-038ab22da0f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='Preview &amp; Submission']</value>
      <webElementGuid>588100ec-a0ed-4c6d-9332-772936484963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div[5]</value>
      <webElementGuid>4ce0a7b0-b9ac-4bd4-82b7-6047df289289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporting Document'])[1]/following::div[1]</value>
      <webElementGuid>ad9885a6-0825-4387-9bec-e5175bd88249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Option'])[1]/following::div[2]</value>
      <webElementGuid>7df594d5-df39-4163-8a93-7920f0d5d46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPPORTING DOCUMENTS'])[1]/preceding::div[1]</value>
      <webElementGuid>2a872683-3f36-41bf-ac8a-ebbc037fb3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]</value>
      <webElementGuid>1862d2cc-e60c-4186-b493-60a867c45cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'Preview &amp; Submission' and @title = 'Preview &amp; Submission' and (text() = 'Preview &amp; Submission' or . = 'Preview &amp; Submission')]</value>
      <webElementGuid>8f66a248-d3cc-4427-8a63-89d41483161a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
