<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter the Address_singleLineText25</name>
   <tag></tag>
   <elementGuidId>3763b869-fd2b-44ea-bd09-aacebed17b6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctrlField952</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctrlField952']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84ac89c9-352f-4884-b092-b84a145dde53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>previewCtrlHolder occupiedControl</value>
      <webElementGuid>f5cecdef-5aa4-4d9c-8668-46ef450fd9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>singleLineText25</value>
      <webElementGuid>4fe090c1-b29b-44cb-a6c0-222dd0c4862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlholdername</name>
      <type>Main</type>
      <value>AddressInsuredPersonInfo2</value>
      <webElementGuid>75d7ff08-0a63-490f-a4da-2f86797eb621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controltype</name>
      <type>Main</type>
      <value>SingleLineText</value>
      <webElementGuid>ad37268a-df7b-4f4d-8b59-7ef5466d14e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctrlField952</value>
      <webElementGuid>bea4438c-d626-4f7d-8758-380432883d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>event-configure</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4719e455-26dc-48ca-b759-5fc4408617a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctrlField952&quot;)</value>
      <webElementGuid>1ef1431c-4fbd-4e5e-801d-d78fb5527ac3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctrlField952']</value>
      <webElementGuid>a7b7f4b9-74d8-49e1-a9ba-bc73d9b38511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row13column1']/div</value>
      <webElementGuid>99000d87-0057-42ab-be37-56bd6675a376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the Address'])[1]/following::div[5]</value>
      <webElementGuid>4029aa5f-b3b3-4c7c-a56d-e35eb7aeb17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[5]</value>
      <webElementGuid>896810ac-0ddd-400b-bbce-ebd02078d808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State City Lookup'])[1]/preceding::div[7]</value>
      <webElementGuid>cda4fb89-8196-4aaf-bd8f-51c4370ce879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/preceding::div[11]</value>
      <webElementGuid>cc9bf034-df4b-4894-8846-a43aff480470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div</value>
      <webElementGuid>659ef082-76c0-46ba-b024-ba8f516bb2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'singleLineText25' and @id = 'ctrlField952']</value>
      <webElementGuid>e3399ab3-428d-4a5d-bd52-9ad8b6e3a5e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
