<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Supporting Document</name>
   <tag></tag>
   <elementGuidId>a750d65b-8c0a-4eed-8a72-2b977eebe31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Supporting Document&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='Supporting Document']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3bff50d-5354-4cec-a2aa-ac38d6ab90a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>983853f0-20e9-48e7-9e4d-050123f79766</value>
      <webElementGuid>824fa359-a7e9-4b10-8e32-87188c635812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSectionProgressBarCell active</value>
      <webElementGuid>f9850f3b-9044-4d3c-a4a1-d194d5cad2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c9b572fd-104c-48fb-9bca-43f37d0cdf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ba747f73-a9e7-429c-9e62-6bf651020df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Supporting Document</value>
      <webElementGuid>c4b4a0a3-c848-44ff-8fbb-51f8e5c75f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Supporting Document</value>
      <webElementGuid>1cf7000f-320a-4c47-9047-b6c2e67dac91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db45583e-5efc-449f-9c8c-496181283c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b4278b4-4d06-4222-9b8c-40a3d1b1ab04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supporting Document</value>
      <webElementGuid>710bcaaf-ae66-4a5e-9b83-1aba491883e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionTabs&quot;)/div[@class=&quot;formSectionProgressBarCell active&quot;]</value>
      <webElementGuid>f2561cbb-8f86-42da-a0d4-9c58587df402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='Supporting Document']</value>
      <webElementGuid>b558fe30-e98c-4cf5-aa33-1c324d8b0f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div[4]</value>
      <webElementGuid>43050bef-3c8a-4a73-ad0b-0de70c23b066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Option'])[1]/following::div[1]</value>
      <webElementGuid>f39f3d41-0160-4cc1-86f1-e072f101f023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revision Information'])[1]/following::div[2]</value>
      <webElementGuid>05de92ed-6559-40ae-9b1b-e6fcd1272577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview &amp; Submission'])[1]/preceding::div[1]</value>
      <webElementGuid>448f218e-7b04-4ca4-9e84-8e34ac26bf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]</value>
      <webElementGuid>d5653c8e-779e-4f64-b929-f0e105002146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'Supporting Document' and @title = 'Supporting Document' and (text() = 'Supporting Document' or . = 'Supporting Document')]</value>
      <webElementGuid>269343c3-1d8d-4e19-b233-9058fb0a5d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
