<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Form not available_loader</name>
   <tag></tag>
   <elementGuidId>33090d52-2b29-4e1b-8a85-b139b01791dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.loader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AP_Container']/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cebfdbd4-b38a-4091-907d-03332b5a1fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loader</value>
      <webElementGuid>7ede7392-d9de-4a4c-b44b-9f79401ed5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AP_Container&quot;)/div[@class=&quot;eFormSurface eform-root eform-pc&quot;]/div[@class=&quot;loader&quot;]</value>
      <webElementGuid>58b0ae53-749e-425d-8e40-43d567745878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AP_Container']/div[2]/div[3]</value>
      <webElementGuid>9169317b-51e3-4376-a35a-4a731e4af56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form not available'])[1]/preceding::div[9]</value>
      <webElementGuid>59559a9c-df57-47be-a9b1-6ace304a7c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Norazrin binti Jumaat'])[1]/preceding::div[13]</value>
      <webElementGuid>9ba09982-957c-4f18-b5da-271cef87ef8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>733a63d3-1821-4efc-a1e9-20d07cb7a319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
