<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AddressInsuredPersonInfo</name>
   <tag></tag>
   <elementGuidId>be85e567-91a6-4ba6-b0c3-9d42f79516db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressInsuredPersonInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressInsuredPersonInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c45cf19-48e6-424e-b04d-97ac53f9cec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba91646a-80bb-4837-b7b3-2b24e340e99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>c84e0f51-06d9-446e-b355-e854b3b46541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressInsuredPersonInfo</value>
      <webElementGuid>4913cbf7-dece-4db1-ac7e-428830ef8dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>18109512-aacb-4a0b-abdc-9c04860caff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressInsuredPersonInfo&quot;)</value>
      <webElementGuid>b41e9742-742f-4cb3-8e93-ec39cbededde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressInsuredPersonInfo']</value>
      <webElementGuid>a5515d10-3a14-4870-824b-ebddb5b45cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField951']/div/input</value>
      <webElementGuid>528399ed-256b-44d6-b4e4-e6359b10a7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>c526bd5a-85da-4074-bca1-a8d54f96d9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AddressInsuredPersonInfo']</value>
      <webElementGuid>e126082a-b3c5-4132-939f-a082ab508f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
