<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CaseSubStatusDDL_save popActionButtons</name>
   <tag></tag>
   <elementGuidId>93ba9059-393e-4cdf-91ca-ec38615fdd27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.save.popActionButtons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07cf0830-93d7-408c-abc5-cb12075e901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3375ae88-4c0f-40e9-8c26-4252ffc79ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>606a6409-df5b-4f75-b357-bc5332ce2562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save popActionButtons</value>
      <webElementGuid>fa65fdfd-8cbe-4826-b6eb-504e2df02833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:SectionSettings.ActionButtons.saveButtonText</value>
      <webElementGuid>c14b6e98-ead9-4e5e-b5a9-492be5fb28f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>471654ba-6def-46a9-a402-18791e5a3b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionButtons&quot;)/div[@class=&quot;formActionButtonsWrapper bottom right&quot;]/input[@class=&quot;save popActionButtons&quot;]</value>
      <webElementGuid>9b8b2d2a-031c-4727-9e13-c40078929247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Save']</value>
      <webElementGuid>60d8a954-0941-4f5f-97b7-535f3a14d46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionButtons']/div/input</value>
      <webElementGuid>d2d09aa5-6662-4c8a-b18f-44e4119bf6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>78e3e067-7d8c-4c5b-987e-1c81113177f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Save']</value>
      <webElementGuid>86fb3d67-7e40-4600-b680-21ef397d94a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
