<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HUS Status_popActionButtons btnSummar_0363f4</name>
   <tag></tag>
   <elementGuidId>6adbc0c3-78a2-42c2-9ad6-e66eed3b99bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.popActionButtons.btnSummaryColumnsOK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='OK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e866138-9f7d-4222-b22b-5ea87b66eb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b969d09-2eec-49ec-83cc-752155735c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]Message.Common.OK</value>
      <webElementGuid>dac1424b-ba7d-4d23-bc1b-516e3fd5a5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popActionButtons btnSummaryColumnsOK</value>
      <webElementGuid>d6ed63ec-7551-461c-a468-56f384ab4055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>0d6a5012-7f1c-47fb-b547-c388ef733a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubForm1&quot;)/div[@class=&quot;subFormContentRow visibleRow summaryColumnsNewRow&quot;]/div[@class=&quot;summaryColumnsPopupButtonsWrapper&quot;]/input[@class=&quot;popActionButtons btnSummaryColumnsOK&quot;]</value>
      <webElementGuid>6a175a30-a707-412e-9b38-c8d245f9bc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='OK']</value>
      <webElementGuid>45845dc1-6f74-4bfc-938e-caa443eaee14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubForm1']/div/div[2]/input[2]</value>
      <webElementGuid>104e031c-caa4-4448-8fce-1c002d160d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input[2]</value>
      <webElementGuid>05711ca3-3e5b-4115-beb7-a923bd735675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c0f546be-dfac-4fc7-b795-3e7a48699758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
