<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NameandAddressofClinicHospitalwhichP_250508</name>
   <tag></tag>
   <elementGuidId>3532a4e9-c8e2-42d3-a2fd-2b88a678f9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25da5545-2ef6-4f4d-8c4b-45e9adb5e244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>479570da-12a8-4338-b3be-c9627f2dd060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field</value>
      <webElementGuid>80144a4f-e9ab-4de0-8529-29da9292887b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>3c479642-d445-4d8c-8c14-e58bd2bd8069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78</value>
      <webElementGuid>b00a4e1f-6335-4704-92c3-dccbb514e5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78&quot;)</value>
      <webElementGuid>68077706-682e-4342-a547-1ee16a09146f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78']</value>
      <webElementGuid>31cc4bdc-136d-4f12-bf48-f89d83c5f498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow4column1-f444-431c5-9c11-4661']/div/div/input</value>
      <webElementGuid>6c68b7c6-e160-4365-8a0d-07730e87c332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>51a9acbf-18cc-4eee-aedc-cc5b74196e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NameandAddressofClinicHospitalwhichProvidesTreatment-c01fd7dd-862e-4e66-aedd-cc7a8986cc78']</value>
      <webElementGuid>a5cb1b02-3d56-4813-8c09-b0bdcf86e43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
