<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PaymentOptionReceivedDate</name>
   <tag></tag>
   <elementGuidId>52a4b40e-e94c-4227-ba07-68aed309e814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaymentOptionReceivedDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PaymentOptionReceivedDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14d8c06b-712f-4021-bdd8-c1e7e3f14758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a57479d8-e8bd-470b-a2cd-2f81709ecfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field datepicker hasDatepicker</value>
      <webElementGuid>0c1bbb53-58e4-4d6d-bf3e-b1cb810e7303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymentOptionReceivedDate</value>
      <webElementGuid>f02fdad6-e798-4ead-b212-190f60c051ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1ad4d0e1-86c9-41c9-b500-9d8ad62fe661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentOptionReceivedDate&quot;)</value>
      <webElementGuid>7dbc72ee-5be4-4a14-a8df-bc5d62cb31a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PaymentOptionReceivedDate']</value>
      <webElementGuid>5a3c7d4d-78e4-4353-b823-8c634b0cc5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField603']/div/input</value>
      <webElementGuid>d1071059-7c47-4354-8fe1-6a7614be7d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
      <webElementGuid>549b9c8a-052f-4c0a-a27d-a8cbc1167989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PaymentOptionReceivedDate']</value>
      <webElementGuid>0dd403d9-046a-46b2-9ed8-9192588ba3c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
