<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NoticeandBenefitClaimFormReceivedDate1</name>
   <tag></tag>
   <elementGuidId>407851ca-7afb-4de8-af3f-080559a100a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NoticeandBenefitClaimFormReceivedDate1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoticeandBenefitClaimFormReceivedDate1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e21db31-33ee-4c0d-9a65-9f8985ff75c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc5ef15e-a6b6-4c7f-9706-3fe9839d53f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field datepicker hasDatepicker invalid-field</value>
      <webElementGuid>9745e91f-e09b-42cd-8e22-e6ee7f809e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoticeandBenefitClaimFormReceivedDate1</value>
      <webElementGuid>76c9da5d-cb1c-4f3e-ba0f-67c36f7ba6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoticeandBenefitClaimFormReceivedDate1&quot;)</value>
      <webElementGuid>9bd83995-0d84-4e10-9adb-0257145885ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoticeandBenefitClaimFormReceivedDate1']</value>
      <webElementGuid>75c7555d-affa-4774-9214-9f7845ada858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField761']/div/input</value>
      <webElementGuid>c2614c3e-ac69-46f8-92b3-8ad4bba5204e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>35e2ac6b-9c24-4f22-b702-3f9ca378ac3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NoticeandBenefitClaimFormReceivedDate1']</value>
      <webElementGuid>f2fef7c7-74cd-45ee-8ee9-1e04ece04d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
