<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BankBranch</name>
   <tag></tag>
   <elementGuidId>6ac06ecb-5ce9-4beb-82e6-cc33afb0caf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BankBranch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BankBranch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caad1c91-d6d0-43a0-a24a-b6b250bb31dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5ae3703-5183-4292-a091-aee4f27725e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field</value>
      <webElementGuid>b7cd0134-55e8-4b14-b91f-ca1b66f6a6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BankBranch</value>
      <webElementGuid>5ebdbcab-bb2f-4715-a501-4f358d6f81b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0efd77e0-1eb6-4e26-9bf9-3861ebd5d8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BankBranch&quot;)</value>
      <webElementGuid>93d4736a-b063-41d3-b052-6d4fcda72dcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BankBranch']</value>
      <webElementGuid>124f2c5a-85e1-484b-9cd4-75b2a1d20697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1044']/div/input</value>
      <webElementGuid>efdf5526-5a4a-41c6-8cb4-24127bd39b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>78008185-6fb1-46c3-82a8-61e5cb27c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'BankBranch']</value>
      <webElementGuid>b91414b2-e9bd-41dc-a30e-71b6d3c71bd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
