<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DesignationEmployerCert</name>
   <tag></tag>
   <elementGuidId>228b2831-f079-4d06-98b0-e7346dc4440d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DesignationEmployerCert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DesignationEmployerCert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66107308-70f7-4cb0-b1d4-44b64a84ae6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0132aa2c-47a9-494f-886f-8ae319be82d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>cbb5f07a-f864-4500-8cf3-c4226e3a3409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DesignationEmployerCert</value>
      <webElementGuid>fdf63af1-0279-496d-9f32-dd6c5dea4c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>7787bc62-f99e-4d88-939b-b0a6685ec447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DesignationEmployerCert&quot;)</value>
      <webElementGuid>f89d421c-b8f6-4f3d-aa0e-8ac2b6bee9c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DesignationEmployerCert']</value>
      <webElementGuid>e53b0bd5-17bd-43fa-bc13-e32d34c5ee30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1212']/div/input</value>
      <webElementGuid>e4a0ad1d-d2aa-4f64-8f4f-caaba09d3ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9ae99880-68d2-4e66-8a81-6600a1566777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DesignationEmployerCert']</value>
      <webElementGuid>6d4a94a1-6c3f-4a61-9928-9ea0947a1fb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
