<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PostcodeInsuredPersonInfo</name>
   <tag></tag>
   <elementGuidId>14d5affa-13d5-4557-b77d-3ffbab69b069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PostcodeInsuredPersonInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PostcodeInsuredPersonInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f244bdf1-1ae7-41d8-b63e-5188b32d2c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c022374-6c89-4b1e-892c-7102df43cf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>63342f2e-a300-43f0-b080-772f7c763aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PostcodeInsuredPersonInfo</value>
      <webElementGuid>e49cc3fd-ef2f-4a2c-a7b5-542ac6251fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>0f12a5fb-f8be-4e52-9ef7-cf4487f060be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PostcodeInsuredPersonInfo&quot;)</value>
      <webElementGuid>12369399-c093-4fc0-a211-02d65f59592f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PostcodeInsuredPersonInfo']</value>
      <webElementGuid>3453cada-5712-44d9-984a-41e6839cc228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField954']/div/input</value>
      <webElementGuid>7baa2308-535f-4e4a-bda5-2c0f5fd4f8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[3]/div/div/input</value>
      <webElementGuid>fd6a2b4f-16b9-4e33-8d51-bdf21201dc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PostcodeInsuredPersonInfo']</value>
      <webElementGuid>e147c239-4a5d-4b55-aec6-885cdf9799b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
