<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preview  Submission_ShowPreview</name>
   <tag></tag>
   <elementGuidId>5ef40220-3df9-44fa-9002-b028645267cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ShowPreview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ShowPreview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d14b57f-85a6-4295-8a0c-3b75b5c5a4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51a74c60-8ce7-4d8e-9082-3e8397f9821f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field Button ButtonOriginal</value>
      <webElementGuid>34dc52f3-81e9-4675-bb88-8fd4eae6814e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show Preview</value>
      <webElementGuid>6bf85306-3eac-4021-aa54-1e4181f4e2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShowPreview</value>
      <webElementGuid>cc89fd89-9e31-4687-be33-e89a13e3aabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:Controls.25f81786-50d9-42b9-9988-daa7e260826d.ButtonText</value>
      <webElementGuid>6eee3926-c245-4dbf-ada9-c65cdc8f828d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShowPreview&quot;)</value>
      <webElementGuid>8c43f2b6-3f99-4039-8883-66a60797cca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4886b049-54c9-464c-be65-c6f394376faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ShowPreview']</value>
      <webElementGuid>21674bf9-49bd-4d2c-ac98-b3b60d3f64ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField562']/div/input</value>
      <webElementGuid>94217424-7921-40af-a433-27b8f4fcd2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d6e820aa-f5ef-401a-92cc-f2c2bcb6e85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'ShowPreview']</value>
      <webElementGuid>fdc477e5-fe4e-4f8e-b0f9-29271788c5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField552']/div/input</value>
      <webElementGuid>7e86eb94-1718-4ce5-8b61-c6f0ca1ff59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1108']/div/input</value>
      <webElementGuid>587c63de-3ea6-4428-8727-7d7ca67bc781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
