<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__EndDateMC-84c939e2-002a-4d3e-9a39-09_8dc319</name>
   <tag></tag>
   <elementGuidId>31754475-fdc8-478b-9256-ebb9c89507ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de5749fe-a207-47f4-bbda-3435d9a0e2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2c940ca-cf06-4e5a-bd4d-77bb757bc72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field datepicker hasDatepicker</value>
      <webElementGuid>1b27c2bd-ed02-4590-9bb8-1c43c6c2cb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd</value>
      <webElementGuid>0cb31d6e-e0a9-4277-993b-8148766d8b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd&quot;)</value>
      <webElementGuid>cb5ee7dc-64d5-4771-bec8-7235058aa834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd']</value>
      <webElementGuid>0a05c03b-df00-4e93-bd3e-4302744c9ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow5column2-f254-48e01-a7e9-0597']/div/div/input</value>
      <webElementGuid>d0d6f8d8-0105-4151-b14b-27b84d46b7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>cf1b1333-5029-4f23-99eb-060dafe28c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'EndDateMC-84c939e2-002a-4d3e-9a39-09eb10413bbd']</value>
      <webElementGuid>7b86cddc-62fd-4c1b-a355-fce6a2c885b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
