<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OccupationBasedonForm34</name>
   <tag></tag>
   <elementGuidId>43702c70-bc3f-4994-99e7-a50b3097e51c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OccupationBasedonForm34</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'OccupationBasedonForm34']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OccupationBasedonForm34']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3206718b-2cf4-4438-8f94-403ea40f8ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>592dcb60-8f22-4bbb-bb7d-81e2a260b492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>bfcb9c4a-b8e9-46ea-8549-15ac7b6df2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OccupationBasedonForm34</value>
      <webElementGuid>0f81425d-6be2-462b-a846-a994bcbb7529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e1beb4a4-7ed9-4a57-8e78-88395ff6f14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OccupationBasedonForm34&quot;)</value>
      <webElementGuid>cd1eedd4-2c05-49d2-b6b8-511a11be995d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OccupationBasedonForm34']</value>
      <webElementGuid>82f01617-93b9-4cf4-9711-8752394860fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField9']/div/input</value>
      <webElementGuid>24d3146d-cd2c-4eaa-ac7b-8de56ea176bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>8fbe8b71-a5fb-49c5-abbd-3c9cc98c3b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'OccupationBasedonForm34']</value>
      <webElementGuid>22ee13e0-f5f3-4e61-bb5f-8c4b9d40c03f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
