<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DateEmployerCert</name>
   <tag></tag>
   <elementGuidId>ffaa0585-5ce3-45e1-913d-a14566dfcfc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DateEmployerCert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateEmployerCert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>871ede7c-7ac0-462d-9145-8cf503731ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8eac7e98-86a8-4a77-8f80-fa28278f5b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field datepicker hasDatepicker invalid-field</value>
      <webElementGuid>ba230e94-135d-4d22-9b51-dee57925e430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateEmployerCert</value>
      <webElementGuid>e2970dfd-ea0d-4c0f-a542-d9c5038240a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateEmployerCert&quot;)</value>
      <webElementGuid>16212216-3dda-440b-9c0b-50b887dd6937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateEmployerCert']</value>
      <webElementGuid>1bfa2d51-d5a5-401b-8fa0-c7cddd6bc18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField877']/div/input</value>
      <webElementGuid>7d5f9c06-18c1-47c9-9916-320177920fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/input</value>
      <webElementGuid>2052a382-f0f3-4198-b7da-6f75cbeeda77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DateEmployerCert']</value>
      <webElementGuid>f7f46db8-bcb3-45c9-a47f-1523c1be503e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
