<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BankAccountNo</name>
   <tag></tag>
   <elementGuidId>3e7a8bab-6bce-4e97-a533-04acd8277490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BankAccountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BankAccountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfff905a-51c3-4843-ba54-521f2c57506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe066653-3b46-4068-932a-b70fb8e2f0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field</value>
      <webElementGuid>8e6fbb62-c539-4fbd-ae02-f1836bd9ef4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BankAccountNo</value>
      <webElementGuid>d3352f2d-679e-4a27-a33c-3c35f73a5ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c4927728-aaa6-40d1-89b3-5879b79cd99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BankAccountNo&quot;)</value>
      <webElementGuid>768b20f5-2f5c-4e74-9fa4-41411b299d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BankAccountNo']</value>
      <webElementGuid>512674b2-5c21-4cfe-b111-984b1bf0d910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1043']/div/input</value>
      <webElementGuid>66efb8b4-051d-4141-a586-18d87923b5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/input</value>
      <webElementGuid>40d64b35-3706-465f-ab3b-00611f23f36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'BankAccountNo']</value>
      <webElementGuid>4acafe2a-5c52-47ab-81c6-ee61f8451ca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
