<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NameEmployerCert</name>
   <tag></tag>
   <elementGuidId>f512d9f9-767b-45f2-ac65-865ca8ace3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NameEmployerCert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameEmployerCert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83ce7f44-545e-4878-bfd5-7cd2acb1369a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>644f806e-1be8-4d4c-aa11-527fcae8e8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>e2a03aea-01fe-456f-a270-afb5c553ac09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameEmployerCert</value>
      <webElementGuid>f82a36c8-3fa3-421b-a5fc-b681f765b256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>52d103c3-d82d-43ba-b542-61c1a8f4629c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameEmployerCert&quot;)</value>
      <webElementGuid>57e3dc98-4975-435b-a7fe-2c42dc2b1223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameEmployerCert']</value>
      <webElementGuid>ba665fcc-4d1c-483b-8b6e-1bdb1aad1f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField875']/div/input</value>
      <webElementGuid>c815e9de-df48-4075-8162-f8fcc3826e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>94c12e05-9d31-46d1-938e-aa247b63f4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NameEmployerCert']</value>
      <webElementGuid>0dd9f759-f868-4cf3-9321-fe0791cc9383</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
