<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AddressInsuredPersonInfo2</name>
   <tag></tag>
   <elementGuidId>2ccb5ca6-093e-418e-b5ed-dae93c1b4228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressInsuredPersonInfo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'AddressInsuredPersonInfo2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressInsuredPersonInfo2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b374b9c-cc77-4968-979f-1e5c9f4e0cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f222982-37fe-4cf9-9ace-9197dab9c986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>62dd36c8-46c9-40d8-b431-4de0a0980ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressInsuredPersonInfo2</value>
      <webElementGuid>8bc500a6-d4e2-4b18-b173-a5b12ce8f497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>6734c568-d28d-4666-965a-254ac2a78357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressInsuredPersonInfo2&quot;)</value>
      <webElementGuid>f6abc14e-5fdd-4535-949c-d738354938a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressInsuredPersonInfo2']</value>
      <webElementGuid>ffc3cd02-9686-4ad4-bf49-75c7d96ca6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField951']/div/input</value>
      <webElementGuid>d13adb09-9ec3-40f9-b666-a5bf57ff78c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>a5e33ef7-f509-4cab-aa6f-70e3020a24c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AddressInsuredPersonInfo2']</value>
      <webElementGuid>da25733f-1258-49de-98ee-ba3227e054e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
