<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__AddressInsuredPersonInfo3</name>
   <tag></tag>
   <elementGuidId>32964a58-3db6-47d5-a603-83da5d6e3cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressInsuredPersonInfo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'AddressInsuredPersonInfo3']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressInsuredPersonInfo3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5c282df-be5e-4bd3-b37d-b4471766731a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>711db1c2-4fa4-4d51-ac36-d1f204e3f7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>4f1fb15f-910a-409c-b335-93079e378ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressInsuredPersonInfo3</value>
      <webElementGuid>031d0393-bc11-453c-bd74-1f8fe949902e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>dc0afb42-376f-4f12-95f1-9dc95b62eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressInsuredPersonInfo3&quot;)</value>
      <webElementGuid>dc59499b-28be-4092-a6da-5848bf522645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressInsuredPersonInfo2']</value>
      <webElementGuid>a3909294-0943-440e-a993-8bf8d0c824c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField951']/div/input</value>
      <webElementGuid>357d91f4-a563-43b0-818b-410a8411b376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>6e806377-2708-4608-8015-e9f7dbb62004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'AddressInsuredPersonInfo3']</value>
      <webElementGuid>a22b4d47-abb3-43eb-9ab4-85286de7010f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
