<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StartDate-cee5f3b0-d7f0-4419-99ad-31_c57f8d</name>
   <tag></tag>
   <elementGuidId>c4908482-ad9c-475e-8796-5032740c4f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66ad6761-d2d3-4eab-a60b-b56ee1099726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba6813c4-0a51-404d-81e7-0ef5791a3322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field datepicker hasDatepicker</value>
      <webElementGuid>11ee7613-d683-46bd-9dc5-7dc11893021c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed</value>
      <webElementGuid>2e6d91d7-95f6-4005-9a79-8881d71924a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed&quot;)</value>
      <webElementGuid>27c51374-8407-4616-bf84-d78a50740085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed']</value>
      <webElementGuid>6bc75b15-b223-44ad-b39c-5ccfc6ece69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow5column1-1558-4edd3-b1d5-2e7a']/div/div/input</value>
      <webElementGuid>e8e13ea2-fef2-433b-b040-83b631b1020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>4161de70-77c7-4536-b7f4-1a7b47b79a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'StartDate-cee5f3b0-d7f0-4419-99ad-3129504acaed']</value>
      <webElementGuid>1dc9ef1c-f00f-4efb-8cd9-d2c61304ce30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
