<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total (Days)_addSubFormRow subFormAct_98634f</name>
   <tag></tag>
   <elementGuidId>eb4a5cb2-b154-4868-97d8-cd7c259596b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubForm1 > div.subFormFooterWrapper > input.addSubFormRow.subFormActionButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>997e5778-ebf7-4765-a323-e9a70d203b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e44add4a-0947-407d-9381-51d472d0f17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[title]Message.Runtime.SubForm.AddRecordHelpText</value>
      <webElementGuid>bf401a9e-5574-42ce-ab8c-dd870986f223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Record</value>
      <webElementGuid>db308962-d981-48b5-a682-c3918928333a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addSubFormRow subFormActionButton </value>
      <webElementGuid>e391841a-7d33-4f5b-ad83-8221509ded8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubForm1&quot;)/div[@class=&quot;subFormFooterWrapper&quot;]/input[@class=&quot;addSubFormRow subFormActionButton&quot;]</value>
      <webElementGuid>ec12b95e-e1d9-407e-a5b8-a85614492f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[10]</value>
      <webElementGuid>2588542b-755e-459e-9b18-15f5a417e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubForm1']/div/input[3]</value>
      <webElementGuid>fe93d923-6371-483a-9b95-08f8abf978ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div/input[3]</value>
      <webElementGuid>ce0f1f60-5afc-414a-89f9-a7de59d4386b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Add Record']</value>
      <webElementGuid>4bf9441e-a8a1-411f-9bd3-39e8d9b35368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
