<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remarks</name>
   <tag></tag>
   <elementGuidId>e1a3312c-a4c3-4fb2-8632-fe9bc0cea283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectionTabs']/div/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Remarks' or . = 'Remarks')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Remarks&quot;] > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6040b113-5ba6-449e-bbea-495208e84880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>translation:SectionSettings.Sections.a1585d22-3a68-4a19-b39d-4904f9d19c3d.DisplayName</value>
      <webElementGuid>c52644ba-29a7-4fc7-b56f-21ab57035401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remarks</value>
      <webElementGuid>66e39dd7-2e29-43b0-9d57-83e1ccedf1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionTabs&quot;)/div[@class=&quot;formSectionProgressBarCell active&quot;]/label[1]</value>
      <webElementGuid>eb4d1ad9-4121-402b-88bc-af8b61f85c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div/label</value>
      <webElementGuid>26a21fa7-afb9-45aa-8bae-88c1ff2474d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form submission cancelled'])[1]/following::label[1]</value>
      <webElementGuid>9eec54aa-5726-4c6a-a496-f0a4cb68f342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form submitted successfully'])[1]/following::label[1]</value>
      <webElementGuid>f757c72a-1b57-47ce-9ba7-a1930ef6534b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revision Information'])[1]/preceding::label[1]</value>
      <webElementGuid>417c1bca-c343-4728-b813-ac9904493dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Option'])[1]/preceding::label[2]</value>
      <webElementGuid>06b92b35-c636-42a2-b2fb-a429004294e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remarks']/parent::*</value>
      <webElementGuid>ab4f4892-09b1-40c0-9f71-6c68e9a4379e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>49b7d587-e54a-4b75-af8b-f7daa352c2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remarks' or . = 'Remarks')]</value>
      <webElementGuid>ee981a3c-e65c-400c-aa02-08beb97d1843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Information'])[1]/preceding::label[1]</value>
      <webElementGuid>52167c54-1032-421c-a77a-11ac3f938ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured Person Information'])[1]/preceding::label[2]</value>
      <webElementGuid>1d308e27-1e4f-42e8-afff-0d49bf353e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
