<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Preview  Submission</name>
   <tag></tag>
   <elementGuidId>2aa70309-aaf4-48f1-a2c3-2851aeb2cbdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Preview &amp; Submission&quot;] > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectionTabs']/div[5]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b1c6e016-cc36-48eb-b2bb-52e29bd9ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>translation:SectionSettings.Sections.c7181999-d582-4aca-b136-e8d5d5b7db04.DisplayName</value>
      <webElementGuid>6aa9439e-de64-4f46-9123-50ce665feae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview &amp; Submission</value>
      <webElementGuid>81ad1dc4-98d6-46b9-a1a8-32b0a7f92fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionTabs&quot;)/div[@class=&quot;formSectionProgressBarCell active&quot;]/label[1]</value>
      <webElementGuid>635488c8-d9d6-4b5e-b7b8-30d3a1b2f199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div[5]/label</value>
      <webElementGuid>a15af292-24ff-4ea5-8992-3eaa3911afa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporting Doc'])[1]/following::label[1]</value>
      <webElementGuid>6cf88d9c-6e5a-4ccd-8102-f86baa543f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Endorsement'])[1]/following::label[2]</value>
      <webElementGuid>3f3eeba2-6fce-4209-82a7-2cc0da55180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPPORTING DOCUMENTS'])[1]/preceding::label[1]</value>
      <webElementGuid>9886785d-d0e8-4d96-aaf2-85ca54ff8179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporting Documents'])[1]/preceding::label[1]</value>
      <webElementGuid>4f776a09-a5a3-4d99-a39f-ce3841c4eec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview &amp; Submission']/parent::*</value>
      <webElementGuid>40165660-3c95-4804-babc-31e4281780c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>ab48413d-1bbc-4011-8400-dfe39240c0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Preview &amp; Submission' or . = 'Preview &amp; Submission')]</value>
      <webElementGuid>30a28171-bb22-47c4-89a3-bc49ffba0d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div[15]/label</value>
      <webElementGuid>a5b5b7b7-f9d7-483d-b2f1-7cd59bf200ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate'])[1]/following::label[1]</value>
      <webElementGuid>c65ecc22-b869-49cb-b25a-53ab278a79db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporting Document'])[1]/following::label[2]</value>
      <webElementGuid>2cdfc0cd-0eeb-4194-98f3-5337e1acae19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Remarks'])[1]/preceding::label[1]</value>
      <webElementGuid>0c231598-6504-4527-b3f3-d524047b695a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::label[2]</value>
      <webElementGuid>9f46566e-cb10-47f9-8837-90b70bd53246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/label</value>
      <webElementGuid>10252058-9322-4974-b707-a151b9110830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
