<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Remarks</name>
   <tag></tag>
   <elementGuidId>e1a3312c-a4c3-4fb2-8632-fe9bc0cea283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Remarks&quot;] > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectionTabs']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cd470429-81d2-4c27-a7d4-d9bb1ca421e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>translation:SectionSettings.Sections.a1585d22-3a68-4a19-b39d-4904f9d19c3d.DisplayName</value>
      <webElementGuid>5820a11c-5a11-450a-8e17-78823680581b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remarks</value>
      <webElementGuid>e6267f76-b1a9-4dee-a4ad-de6f09bd9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionTabs&quot;)/div[@class=&quot;formSectionProgressBarCell active&quot;]/label[1]</value>
      <webElementGuid>a9a0a335-ad32-4194-a396-0cd08f74a912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionTabs']/div/label</value>
      <webElementGuid>61048491-a36d-46d4-aade-be74cfde4073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form submission cancelled'])[1]/following::label[1]</value>
      <webElementGuid>ef566121-b6de-4c69-a953-e88e592fc774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form submitted successfully'])[1]/following::label[1]</value>
      <webElementGuid>f1374107-03e6-429f-9b9d-463c863f878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revision Information'])[1]/preceding::label[1]</value>
      <webElementGuid>41d61d7c-9c15-4e96-ae05-ef58d8068fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Option'])[1]/preceding::label[2]</value>
      <webElementGuid>c3cf88b1-e59c-4016-b47b-88cdf7f5343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remarks']/parent::*</value>
      <webElementGuid>88b56dca-ab2d-4875-ba7c-69b1ffc6f560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>2e771553-80ae-47e3-af47-b7dce6d2414a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remarks' or . = 'Remarks')]</value>
      <webElementGuid>186627cb-f679-4df7-b483-f468f3f444eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Information'])[1]/preceding::label[1]</value>
      <webElementGuid>f80baa61-e03d-46a1-a855-5a4a81eba459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured Person Information'])[1]/preceding::label[2]</value>
      <webElementGuid>f89ce2a0-2fb4-43cc-a670-830623d5c77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
