<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectRASASEMENYIHBUKIT ROTAN_9c7f7b_1</name>
   <tag></tag>
   <elementGuidId>cb12db1f-3ccc-4564-933a-b20bf1cd4386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c27057f7-fee3-42d0-9dd7-798e30360f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>0adaa5f9-f3b8-4597-b62f-048e5c94525b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb</value>
      <webElementGuid>a4cb16fd-0e59-4fa3-bcad-92f57a486f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectRASASEMENYIHBUKIT ROTANSEPANGPULAU KETAMSUNGAI BESARKUALA SELANGORSHAH ALAMKAJANGBANDAR BARU BANGIKAPARPUCHONGKLANGSABAK BERNAMDENGKILKLIABATU CAVESPETALING JAYASUNGAI AYER TAWARBATU ARANGPANDANSERI KEMBANGANSUNGAI PELEKTELOK PANGLIMA GARANGTANJONG KARANGSUNGAI BULOHSERDANGCYBERJAYATANJONG SEPATKUALA KUBU BHARUBANTINGSUBANG AIRPORTHULU LANGATSERENDAHJENJAROMSUBANG JAYAKERLINGRAWANGCHERASBANGIBANDAR PUNCAK ALAMBERANANGPELABUHAN KLANGJERAMAMPANGPULAU INDAHSEKINCHANBATANG KALIGOMBAKPULAU CAREYBATANG BERJUNTAIBANDAR SUNWAYULU SELANGORKUALA LANGAT</value>
      <webElementGuid>f181fecc-56ba-4f6b-bbf8-d5571c65689b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb&quot;)</value>
      <webElementGuid>1b0ac699-48d0-45ce-a305-ce7f815e4f9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb']</value>
      <webElementGuid>0c74a7c8-c182-4efd-b36c-9852cd903576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow7column2-0ceb-401de-b08b-4231']/div/div/select</value>
      <webElementGuid>8b88fec8-363e-4658-a082-f95dda7f4af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::select[1]</value>
      <webElementGuid>bf54643f-0025-4df7-aa6a-89efcf50fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[4]/following::select[1]</value>
      <webElementGuid>175c7120-5b36-429b-8e97-f3b4cf278f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postcode'])[4]/preceding::select[1]</value>
      <webElementGuid>789f5daf-522c-4669-b5e6-e860b5cfb0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[17]/preceding::select[1]</value>
      <webElementGuid>48e9e1a1-3d2d-44d2-985d-53f6d8c7a0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/div/div[7]/div[2]/div/div/select</value>
      <webElementGuid>5f20eedc-56df-4ca4-b7d5-af8ef196b8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'City_inEmp-19fd51b3-0506-490a-a490-0519aef3c1bb' and (text() = 'Please SelectRASASEMENYIHBUKIT ROTANSEPANGPULAU KETAMSUNGAI BESARKUALA SELANGORSHAH ALAMKAJANGBANDAR BARU BANGIKAPARPUCHONGKLANGSABAK BERNAMDENGKILKLIABATU CAVESPETALING JAYASUNGAI AYER TAWARBATU ARANGPANDANSERI KEMBANGANSUNGAI PELEKTELOK PANGLIMA GARANGTANJONG KARANGSUNGAI BULOHSERDANGCYBERJAYATANJONG SEPATKUALA KUBU BHARUBANTINGSUBANG AIRPORTHULU LANGATSERENDAHJENJAROMSUBANG JAYAKERLINGRAWANGCHERASBANGIBANDAR PUNCAK ALAMBERANANGPELABUHAN KLANGJERAMAMPANGPULAU INDAHSEKINCHANBATANG KALIGOMBAKPULAU CAREYBATANG BERJUNTAIBANDAR SUNWAYULU SELANGORKUALA LANGAT' or . = 'Please SelectRASASEMENYIHBUKIT ROTANSEPANGPULAU KETAMSUNGAI BESARKUALA SELANGORSHAH ALAMKAJANGBANDAR BARU BANGIKAPARPUCHONGKLANGSABAK BERNAMDENGKILKLIABATU CAVESPETALING JAYASUNGAI AYER TAWARBATU ARANGPANDANSERI KEMBANGANSUNGAI PELEKTELOK PANGLIMA GARANGTANJONG KARANGSUNGAI BULOHSERDANGCYBERJAYATANJONG SEPATKUALA KUBU BHARUBANTINGSUBANG AIRPORTHULU LANGATSERENDAHJENJAROMSUBANG JAYAKERLINGRAWANGCHERASBANGIBANDAR PUNCAK ALAMBERANANGPELABUHAN KLANGJERAMAMPANGPULAU INDAHSEKINCHANBATANG KALIGOMBAKPULAU CAREYBATANG BERJUNTAIBANDAR SUNWAYULU SELANGORKUALA LANGAT')]</value>
      <webElementGuid>5ca2312c-ece7-486d-a172-d856fb193f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
