<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectYesNo</name>
   <tag></tag>
   <elementGuidId>a8f7380d-d872-4737-b298-38b4ce051585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AccountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>886c7133-1a42-4081-bedf-470d246d7de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>0c69d256-54af-4657-827f-b8ffecbe66d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountNo</value>
      <webElementGuid>7ede2483-0752-4bb5-b7c3-e84d11df82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectYesNo</value>
      <webElementGuid>89a26500-741f-43f3-ba03-0bf5eebaa4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountNo&quot;)</value>
      <webElementGuid>41b7f495-85c7-46dd-83cf-dd1a2172fc2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AccountNo']</value>
      <webElementGuid>7470cb8f-1535-4316-94da-62ef50e7ffe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1092']/div/select</value>
      <webElementGuid>9280771d-0b1d-464d-9b51-beefc0593968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>1682c1af-80ce-4096-9982-5a8545b165d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No.'])[1]/following::select[1]</value>
      <webElementGuid>f33f3ffd-2628-40c5-8ece-627986afdf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from Account No.'])[1]/preceding::select[1]</value>
      <webElementGuid>07874be7-bcd4-4219-a60b-b2532a458fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Location'])[1]/preceding::select[1]</value>
      <webElementGuid>1e6d73c3-1a73-4262-83bf-ebe81f471187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>8ababda7-dbcc-4aed-ada6-91e6d54c806a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AccountNo' and (text() = 'Please SelectYesNo' or . = 'Please SelectYesNo')]</value>
      <webElementGuid>ab5304c1-3e82-4d3c-98e9-5ebfdc1be1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
