<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectLump SumPeriodical</name>
   <tag></tag>
   <elementGuidId>7ebaa9c4-837b-4e4c-8b62-ad00e46ff277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaymentOption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PaymentOption']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dbb60aea-e333-473d-866a-85e38724c34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field</value>
      <webElementGuid>06582051-e64f-42a2-b607-6dda31796695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymentOption</value>
      <webElementGuid>1bc4c30e-7b0c-41cb-ae9e-037d8f78ef66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>edb58266-6478-4541-9e38-f1a36a9f10f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectLump SumPeriodical</value>
      <webElementGuid>88048ec4-d553-4639-9d00-1b2801b8edad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentOption&quot;)</value>
      <webElementGuid>2c21b1e9-49ea-478a-ad66-5d3e7b13a6b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PaymentOption']</value>
      <webElementGuid>871c1e4a-738e-42b6-b421-a0afb0c50766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField601']/div/select</value>
      <webElementGuid>42576c77-665e-4d1c-8b14-b64fae58a11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>190df220-6ac8-4d7e-9b20-4596cbb29f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Option'])[3]/following::select[1]</value>
      <webElementGuid>9fe6b251-b858-458f-86a2-c356385b549b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment %'])[1]/preceding::select[1]</value>
      <webElementGuid>146e26c2-f449-4dd0-a56a-5f2c133bf9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='huk assessment'])[1]/preceding::select[1]</value>
      <webElementGuid>6dfcc40d-3e29-4a02-829d-5a78fce5564e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>5d9f1e66-a70f-400a-a152-554cad007dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PaymentOption' and (text() = 'Please SelectLump SumPeriodical' or . = 'Please SelectLump SumPeriodical')]</value>
      <webElementGuid>2afc0bf3-1bf5-4d85-b4a4-809a2e811366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
