<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_State_Employer_Info</name>
   <tag></tag>
   <elementGuidId>a81171b7-affa-4949-bf71-3eab7ebd287e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddStateIPI</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;State_inEmp-99a285b1-28bc-4668-a928-8b843faa01cd&quot;)[count(. | //*[@id = 'State_inEmp-99a285b1-28bc-4668-a928-8b843faa01cd']) = count(//*[@id = 'State_inEmp-99a285b1-28bc-4668-a928-8b843faa01cd'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AddStateIPI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6845693-44b8-402d-afaa-bacb317f8d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>17415dc5-5d06-485f-80ec-7b745f53c1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>State_inEmp-99a285b1-28bc-4668-a928-8b843faa01cd</value>
      <webElementGuid>cf1d9a06-9db6-4701-88a4-0c97e1b8d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPERAKPERLISPULAU PINANGSABAHSARAWAKSELANGORTERENGGANUTIDAK DIKETAHUIWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYA</value>
      <webElementGuid>eb1cc102-a966-4c1a-8587-0b41e95db523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;State_inEmp-99a285b1-28bc-4668-a928-8b843faa01cd&quot;)</value>
      <webElementGuid>f5975980-e178-4e73-846a-8bbd25bff063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AddStateIPI']</value>
      <webElementGuid>84e7fe96-c145-4e94-aaac-c0f1e0cabcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1484']/div/select</value>
      <webElementGuid>448d152e-0c86-4f11-8f57-5b8774cebe55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>3cc5ac2b-c35d-4ff4-937c-80821d1216b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>02c590c2-8806-4511-b0f5-295e3d4038e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from State'])[1]/preceding::select[1]</value>
      <webElementGuid>cf53b78c-34fa-4d69-bef1-e211c8e3b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::select[1]</value>
      <webElementGuid>4cb499a5-cd92-4947-b0d9-e547e9791e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/select</value>
      <webElementGuid>5f872ca2-cb2c-4eab-b3d1-cd75610859a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AddStateIPI' and (text() = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPERAKPERLISPULAU PINANGSABAHSARAWAKSELANGORTERENGGANUTIDAK DIKETAHUIWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYA' or . = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPERAKPERLISPULAU PINANGSABAHSARAWAKSELANGORTERENGGANUTIDAK DIKETAHUIWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYA')]</value>
      <webElementGuid>d6b95b33-2cc3-4c58-9d41-55113bff5fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
