<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectSavingCurrent</name>
   <tag></tag>
   <elementGuidId>8c95a23d-6b42-4771-8817-9d33d15642d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BankAccountType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BankAccountType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>265e0237-f120-4922-9bc4-050bbba7de09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field</value>
      <webElementGuid>278eb6ed-8310-40e1-bbd5-0d4984893224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BankAccountType</value>
      <webElementGuid>be713a85-d676-4246-8bdc-7d5e13ec2bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectSavingCurrent</value>
      <webElementGuid>03e2decd-7b7e-4fff-a04f-a9b630ff0a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BankAccountType&quot;)</value>
      <webElementGuid>70ef1a93-64d7-49d4-8063-0e6b8468767e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='BankAccountType']</value>
      <webElementGuid>26eaf523-4c64-4da0-ba32-e2fabd876546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1042']/div/select</value>
      <webElementGuid>edc8dddd-2018-4f9c-b668-e12772bcf5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>7398ff36-3908-4e1c-967f-9f1025c6b744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Type'])[1]/following::select[1]</value>
      <webElementGuid>9df871bf-36a8-4a74-8c2a-f772b572905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account No.'])[1]/preceding::select[1]</value>
      <webElementGuid>2eaa46ba-02d3-4d8f-be28-949e47ec3096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>9e814674-d3da-4aa2-8cf1-1fc8593096a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/select</value>
      <webElementGuid>70fe3b9b-757b-4118-980b-cfcd4b181cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'BankAccountType' and (text() = 'Please SelectSavingCurrent' or . = 'Please SelectSavingCurrent')]</value>
      <webElementGuid>ebd628fe-ee0b-43d3-b499-ce52d20e8007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
