<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Postcode_Employer_Info</name>
   <tag></tag>
   <elementGuidId>40af8bdb-8b44-49b1-b591-35d152e11ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Postcode_inEmp-69a220e4-74fb-4d9f-b33b-6e512a9f60bc&quot;)[count(. | //*[@id = 'Postcode_inEmp-69a220e4-74fb-4d9f-b33b-6e512a9f60bc']) = count(//*[@id = 'Postcode_inEmp-69a220e4-74fb-4d9f-b33b-6e512a9f60bc'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5358bf43-e50f-4501-9343-cb39ba6dd6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>9860bae2-4474-45d2-8bb3-b176897c3b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Postcode_inEmp-69a220e4-74fb-4d9f-b33b-6e512a9f60bc</value>
      <webElementGuid>21f04cd6-2a46-4997-b627-d3c697388981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI</value>
      <webElementGuid>db20cfed-0ad6-46d6-8460-5fbc2a9d0f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Postcode_inEmp-69a220e4-74fb-4d9f-b33b-6e512a9f60bc&quot;)</value>
      <webElementGuid>21c729bf-01e4-497a-bdc5-d153ca11209f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      <webElementGuid>ec8b5c1a-8fc4-4aae-ba54-884d36b6872c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow7column1-5473-4ae7a-b7a5-d020']/div/div/select</value>
      <webElementGuid>e19ef4de-e63f-42fa-9660-8aea9d4934df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::select[1]</value>
      <webElementGuid>17868301-b413-4a7a-a2b2-0a777d6e1771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[4]/following::select[1]</value>
      <webElementGuid>29ea5e2b-5132-4e0b-bf92-e5df3800b8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from State'])[2]/preceding::select[1]</value>
      <webElementGuid>a955c802-c7d0-497f-a0fd-3415d7d2c8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[4]/preceding::select[1]</value>
      <webElementGuid>55ea12fc-d490-4cda-97ba-f2354aecc4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/div/div[7]/div/div/div/select</value>
      <webElementGuid>edcbed12-9fcd-499e-94ee-74fa753199a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8' and (text() = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI' or . = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI')]</value>
      <webElementGuid>25ec8ebd-fd26-4885-a365-4196e12e5233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
