<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectJOHORKEDAHKELANTANMELAK_1b13cf</name>
   <tag></tag>
   <elementGuidId>abf5e76b-2361-4436-aad9-6886fad266b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'CityIPI' and (text() = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI' or . = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>026ad212-e2e0-4ee3-a09b-46fe6263af6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>2c2b678e-a711-48ad-aae0-0322131f3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CityIPI</value>
      <webElementGuid>cbb3fcf9-a19b-4dda-ad4b-5afc47c6cb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI</value>
      <webElementGuid>c846e5ee-6407-4c18-97bb-fb6e1cf4442e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CityIPI&quot;)</value>
      <webElementGuid>f23a174b-abcf-4d66-be37-e68a35c3a2ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      <webElementGuid>ed9bf753-b9fa-40dc-8f1a-bacd04435a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow7column1-5473-4ae7a-b7a5-d020']/div/div/select</value>
      <webElementGuid>fdb76852-2941-48ee-bc2d-7fef692ea7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::select[1]</value>
      <webElementGuid>ebb7830c-e8fc-4ce3-be3d-f4283d86740d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[4]/following::select[1]</value>
      <webElementGuid>0c6aee78-74ef-49bf-93df-f82ed9643e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from State'])[2]/preceding::select[1]</value>
      <webElementGuid>b32b87bc-8346-4fe3-9999-bddf9f64d946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[4]/preceding::select[1]</value>
      <webElementGuid>fab034e2-4b03-40a2-91a4-10beea8052bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/div/div[7]/div/div/div/select</value>
      <webElementGuid>ad0f6322-2761-49f5-931b-699f2482efa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8' and (text() = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI' or . = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI')]</value>
      <webElementGuid>9ffcc969-a178-48ac-bd7f-2793999122c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
