<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectYesNo</name>
   <tag></tag>
   <elementGuidId>a8f7380d-d872-4737-b298-38b4ce051585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AccountNo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'AccountNo' and (text() = 'Please SelectYesNo' or . = 'Please SelectYesNo')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1220531f-86ca-4bde-88d9-e2a8fabf2bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field </value>
      <webElementGuid>05b1f0e2-0888-41e0-ab58-1387a16c35c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountNo</value>
      <webElementGuid>3ae840e9-6c81-4d2b-9eb0-6a025850eaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectYesNo</value>
      <webElementGuid>84eb582e-fb1e-487c-b28f-fd517cc45b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountNo&quot;)</value>
      <webElementGuid>2d35d5ce-decd-4e62-8e38-272f85be4148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AccountNo']</value>
      <webElementGuid>3fb5500d-369b-4322-b6ac-e2682650f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1092']/div/select</value>
      <webElementGuid>00377293-82f8-4d17-9aa1-62dfa1437be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>4f4c900b-1ca5-4244-b988-5cad73289dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No.'])[1]/following::select[1]</value>
      <webElementGuid>dceba35f-5f82-4e0b-916a-87f5a0a214b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from Account No.'])[1]/preceding::select[1]</value>
      <webElementGuid>3d6dc513-ea16-4c86-8186-3d3222147c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Location'])[1]/preceding::select[1]</value>
      <webElementGuid>673df8eb-034f-4be3-bfa9-4f395879e8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>8306e7c7-00c8-42c3-8f20-7cd86ee8d2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AccountNo' and (text() = 'Please SelectYesNo' or . = 'Please SelectYesNo')]</value>
      <webElementGuid>93c00d56-ddc9-4855-bc7c-24da04faa626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
