<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_City_Employer_Info</name>
   <tag></tag>
   <elementGuidId>e30c5015-3e46-4fc6-9b6f-c5c20b7f5901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;City_inEmp-b8b4948a-69aa-4dd4-aeb8-c7051a9fc3f7&quot;)[count(. | //*[@id = 'City_inEmp-b8b4948a-69aa-4dd4-aeb8-c7051a9fc3f7']) = count(//*[@id = 'City_inEmp-b8b4948a-69aa-4dd4-aeb8-c7051a9fc3f7'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>311a5a48-2c34-4ba6-8477-bd927aa042b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field invalid-field</value>
      <webElementGuid>0d558b28-408c-4f38-9558-da0e346dd0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City_inEmp-b8b4948a-69aa-4dd4-aeb8-c7051a9fc3f7</value>
      <webElementGuid>d933cc78-4472-464a-a979-29cd7f159ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI</value>
      <webElementGuid>d4427d92-3133-430f-baa9-1c7feeb9b839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City_inEmp-b8b4948a-69aa-4dd4-aeb8-c7051a9fc3f7&quot;)</value>
      <webElementGuid>612e3753-3000-45b5-8bac-305ed9d07604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8']</value>
      <webElementGuid>c5c9b1c2-350c-4262-b614-cf533f22e984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subCtrlRow7column1-5473-4ae7a-b7a5-d020']/div/div/select</value>
      <webElementGuid>932dab04-e8bd-48dd-9a2a-40d0b0fa3349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::select[1]</value>
      <webElementGuid>e19d7b27-b583-41d6-9ce3-116e886285e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[4]/following::select[1]</value>
      <webElementGuid>d6da988b-745d-46e2-8bd6-9dd13c7c64ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option from State'])[2]/preceding::select[1]</value>
      <webElementGuid>ddfe80ed-1e6d-4f30-88e9-6c81659036aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[4]/preceding::select[1]</value>
      <webElementGuid>1d47729d-8595-485a-9619-473636de3b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[2]/div/div/div[7]/div/div/div/select</value>
      <webElementGuid>cda567a2-aad1-4d19-99dc-6efe5b7707b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'State_inEmp-6dba2a12-7a82-4170-8e61-c1821792e2e8' and (text() = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI' or . = 'Please SelectJOHORKEDAHKELANTANMELAKANEGERI SEMBILANPAHANGPULAU PINANGPERAKPERLISSELANGORTERENGGANUSABAHSARAWAKWILAYAH PERSEKUTUAN KUALA LUMPURWILAYAH PERSEKUTUAN LABUANWILAYAH PERSEKUTUAN PUTRAJAYATIDAK DIKETAHUI')]</value>
      <webElementGuid>7ec25432-ee19-49d0-9a62-cc8cc462a335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
