<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_btnClose</name>
   <tag></tag>
   <elementGuidId>6c939584-aea2-48cf-a958-19023aaa1c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnClose']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btnClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1c0e3b9-dbec-400b-bbfe-97987e3c4251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>e84a34b8-5555-46ed-9c75-d16be0a93217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fh-modal-close</value>
      <webElementGuid>58aa6ea7-cba4-4b1d-89c2-63e22219cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClose&quot;)</value>
      <webElementGuid>17630f76-c687-42f5-85b0-dbe310889427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnClose']</value>
      <webElementGuid>78b76753-f467-4eb7-85dd-b2c2faaded9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-history-modal']/div/div[2]/span</value>
      <webElementGuid>09029a5b-e94a-4c46-bd10-802893631865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/span</value>
      <webElementGuid>0e1d8c95-a9c9-4052-b7ed-79c9b68a6ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnClose']</value>
      <webElementGuid>d3d5ac47-8134-4d36-a715-afec6a4dffab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
