<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Specifydutiesandhowinsuredpersone_db1a46</name>
   <tag></tag>
   <elementGuidId>4c059b95-066d-4dbc-9656-2af694d6accb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Specifydutiesandhowinsuredpersonexposedtothedanger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Specifydutiesandhowinsuredpersonexposedtothedanger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3821a38d-ceac-43b8-acad-49e510596421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>73a1b0ba-97a6-4827-bd62-bf45f505caab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5b58ca88-2115-4608-b1ca-0a0479d6bcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Specifydutiesandhowinsuredpersonexposedtothedanger</value>
      <webElementGuid>f266cb23-87ad-48fa-850c-44a9386f819f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>8a3a647f-7738-4603-9219-2cf5d2a89177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Specifydutiesandhowinsuredpersonexposedtothedanger&quot;)</value>
      <webElementGuid>416ca7e3-eded-4097-9d36-0cd7f0003aaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Specifydutiesandhowinsuredpersonexposedtothedanger']</value>
      <webElementGuid>16738cca-505a-469a-be99-4bbcce4d1ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1393']/div/textarea</value>
      <webElementGuid>d0d9a964-a33b-4b79-86e7-9b002dc28a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/textarea</value>
      <webElementGuid>3c74cbb6-99c1-49e9-a7d7-07eb559fbb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Specifydutiesandhowinsuredpersonexposedtothedanger']</value>
      <webElementGuid>d19bdf6b-5de7-4976-b88c-f99ee22616b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
