<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Pleaseexplainsymptomssignencountered</name>
   <tag></tag>
   <elementGuidId>90db5c89-5259-447e-8c3f-b04d46d3e129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Pleaseexplainsymptomssignencountered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Pleaseexplainsymptomssignencountered']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f4b27a8a-2828-4204-aa68-061243066f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field invalid-field</value>
      <webElementGuid>9660320b-ec5f-4f98-bd61-2b472c006552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>cb473c60-3169-4d6d-b640-027aa97eded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pleaseexplainsymptomssignencountered</value>
      <webElementGuid>811e096f-160e-4c48-b865-ac97f86e6d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>6f777e42-a17d-4dce-aec0-d0213534d53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pleaseexplainsymptomssignencountered&quot;)</value>
      <webElementGuid>f343727d-3d36-4790-ac73-51f223545b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Pleaseexplainsymptomssignencountered']</value>
      <webElementGuid>2af96e33-c97f-49aa-8cbd-c8ab79ecfe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField1394']/div/textarea</value>
      <webElementGuid>3a2d81d1-1dd5-40f4-bbae-fcd263445afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/textarea</value>
      <webElementGuid>03c6e190-2532-4748-818d-6e85032ddff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Pleaseexplainsymptomssignencountered']</value>
      <webElementGuid>4a788764-af23-4586-9fa0-948e5635097b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
