<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Reemployment Scheduler_baristaPageOut</name>
   <tag></tag>
   <elementGuidId>896ba5dc-d8af-4fb2-ae11-0dda2ae612ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#baristaPageOut</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='baristaPageOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c58795b8-086b-4ce9-aa62-c2bbffe74e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>look-ma-no-frames</value>
      <webElementGuid>04ce9951-aac2-47c7-89d0-426f1a83e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>baristaPageOut</value>
      <webElementGuid>7e9af481-3869-4315-831e-bb6f40c78b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/workcenter/TaskList.html?rev=080000012</value>
      <webElementGuid>795e584d-a5f2-46f2-920a-0184cc1c3e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;baristaPageOut&quot;)</value>
      <webElementGuid>eb83685e-fa86-4525-8972-52f41c29b06c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='baristaPageOut']</value>
      <webElementGuid>fbd5578d-e8fc-4f7b-95f2-0cfa387f2291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-builder-root']/div/div/div/div/div/div/div[2]/div/div/iframe</value>
      <webElementGuid>468a4b41-e85c-40d4-b930-3acb4dafc10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6383d9ee-f358-4b94-8144-48c50626687b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'baristaPageOut' and @src = '/workcenter/TaskList.html?rev=080000012']</value>
      <webElementGuid>a6071055-19d5-43d6-8e6e-5c6dabe2363b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'baristaPageOut' and @src = '/appbuilder/formrender?FormApplication=Pre-Registration%20Revision_PreRegistration%20Revision']</value>
      <webElementGuid>e509adc9-b3dd-49c1-b8aa-3fdaf412bd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'baristaPageOut' and @src = '/appbuilder/formrender?FormApplication=Notice%20Pre-Registration_Registration']</value>
      <webElementGuid>9fcf1264-5f9f-4b31-8656-645863691b96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
