<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__SearchOb</name>
   <tag></tag>
   <elementGuidId>10325dc8-2b61-44a5-9cee-c9fefaf5d28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchOb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchOb']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'SearchOb' and @ref_element = 'Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da56e49e-8e22-4002-8066-c230f67286c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdc17927-0003-46b0-8af4-0a072c9486b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field Button ButtonOriginal</value>
      <webElementGuid>1103072d-8c59-4279-9313-3edac7cf4e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>322048d5-0b76-41a5-8e19-3af6a68be919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchOb</value>
      <webElementGuid>24480c42-7e34-4422-beff-3511c84850b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:Controls.a47463c7-5c7b-48bb-88e0-28305213b70b.ButtonText</value>
      <webElementGuid>b50c9939-847c-404e-8030-ae5ef4cfaada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchOb&quot;)</value>
      <webElementGuid>7b034462-6b1b-41fa-ab00-e30a3eaa4112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>1935921b-9c95-4b27-b894-e414da1b9b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchOb']</value>
      <webElementGuid>43a269d8-e6ce-4142-9a6c-7359e1582ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField800']/div/input</value>
      <webElementGuid>c7aa2ea8-67f1-4eab-acb0-bb6ad2d8dadf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>e4bac2ea-b7d7-4151-92bc-5f88f66dbf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SearchOb']</value>
      <webElementGuid>0dbb73ea-1115-427b-b63b-1ba2d58545aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
