<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Case Status_btnCreateRevision-4e6d-4e_b064f9</name>
   <tag></tag>
   <elementGuidId>9d61d7db-9889-43a3-ba96-11e02d3cca0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCreateRevision-4e6d-4ecf4-a02c-c9c5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnCreateRevision-4e6d-4ecf4-a02c-c9c5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e5bcdeb-f1e3-4f7a-9840-504bfce9271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75eee6aa-2b32-4ff2-b4ec-42179fd02f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field Button ButtonOriginal</value>
      <webElementGuid>4e43320e-3446-4518-b772-d1107ee6b543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Revision</value>
      <webElementGuid>74b7a0ad-0ecb-4a5c-8625-62c5bb83755f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCreateRevision-4e6d-4ecf4-a02c-c9c5</value>
      <webElementGuid>6ed503db-aa87-4602-93ca-8a60fb79b83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:Controls.31baa226-eed0-456e-b0a4-800f575c95a2.ButtonText</value>
      <webElementGuid>2f21b12a-8632-4b8d-bfd7-7202cb2caca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCreateRevision-4e6d-4ecf4-a02c-c9c5&quot;)</value>
      <webElementGuid>9537ed10-18b1-4f31-bebb-93b48eb57c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>53c4e700-7aaf-47fe-a837-408ee7f10a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnCreateRevision-4e6d-4ecf4-a02c-c9c5']</value>
      <webElementGuid>9beccd94-89cc-45ee-922b-45ef5b65abfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField52']/div/input</value>
      <webElementGuid>4643bfb1-b747-4d9e-bbdb-e1512268a3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>55fc07c1-fc0b-481c-8929-c123bc2e60a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnCreateRevision-4e6d-4ecf4-a02c-c9c5']</value>
      <webElementGuid>66578ae9-f81c-474b-a0e8-5e86921d60ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
