<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scheme Reference Number_SearchBySchem_dfb478</name>
   <tag></tag>
   <elementGuidId>b205c5d9-c130-4130-8c52-2eed64a4a89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchBySchemeReference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchBySchemeReference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1fb6123-8480-444b-9044-018a9a4da936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>097bd465-e40e-4784-aff2-65310bdb184c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button PopUpSelect field</value>
      <webElementGuid>35e7aac4-eaf4-4192-be7f-b82b9e702c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e4b8a76c-83b3-4d2e-9918-99482b651a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchBySchemeReference</value>
      <webElementGuid>4e6a695e-2de2-46c0-893c-d672d84f944d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:Controls.b91e6328-4178-4940-a7f3-7bdd85098ef1.ButtonText</value>
      <webElementGuid>2968cd7a-d643-4d6a-add8-9cebe1cc36b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBySchemeReference&quot;)</value>
      <webElementGuid>1ea08336-404a-4805-ac63-249c201cf6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>b0d59658-e321-47a4-b506-664ecd94374b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchBySchemeReference']</value>
      <webElementGuid>2c121f11-1c2b-422d-85d4-fa94df469e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField20']/div/input</value>
      <webElementGuid>624f82d0-28cf-4ee5-aea7-06cc6a25a89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/input</value>
      <webElementGuid>e952fa99-be4d-4d9a-8366-c16b240c0f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SearchBySchemeReference']</value>
      <webElementGuid>fa56778b-bc04-41fa-84e6-9de89b3e5644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
