<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__EmployerCodePreReg</name>
   <tag></tag>
   <elementGuidId>790eee5e-c7d5-403f-b30c-e6b9152cb0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmployerCodePreReg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmployerCodePreReg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3db934cc-992a-4002-a274-2de60e53847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c28540d0-ddcc-4fde-bae2-9be952a7c725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field</value>
      <webElementGuid>f87b85c4-7806-4b44-b4e9-f3f9a8c112ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmployerCodePreReg</value>
      <webElementGuid>bd35aac9-3fcd-4198-aa07-0bb63d3b1707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>f8101bfe-e9e5-42ac-aef1-340bf93abc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabledtoolfn</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af245f44-a1bb-4289-a815-3f03ae1a455d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmployerCodePreReg&quot;)</value>
      <webElementGuid>8fd404b0-ce7e-4256-a32f-e6a7b8dc5693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>0d49562a-5e9a-4863-b1cc-a60249bfeed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmployerCodePreReg']</value>
      <webElementGuid>7779c767-68c4-4096-815c-ebf3d82a339f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField641']/div/input</value>
      <webElementGuid>5435849e-1d72-4102-96cc-5e50774fc0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[7]/div/div/div/input</value>
      <webElementGuid>94f4a862-177c-4e2b-bfbf-2295003d87e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'EmployerCodePreReg']</value>
      <webElementGuid>32c06184-204a-4174-a403-38a4d03ed840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
