<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_POC_Next</name>
   <tag></tag>
   <elementGuidId>92f85589-2271-466a-b1f1-5d8f9d903ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Next</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Next&quot;)[count(. | //*[@type = 'button' and @value = 'Next' and @id = 'Next' and @ref_element = 'Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut']) = count(//*[@type = 'button' and @value = 'Next' and @id = 'Next' and @ref_element = 'Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe367e8-3ef6-4875-9218-4ef21364a83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ca3c5c7-440a-4441-8e5d-956a2f17fe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field Button ButtonOriginal</value>
      <webElementGuid>6ad0cf26-2f8e-4f0a-b2b1-8471c29b93a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>5fa6a7c8-6dd3-42b0-be14-66b95ba8e43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>b7e2cd30-174d-4d8f-ab42-4fb668720d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>[value]translation:Controls.e20854a2-bab7-407a-b5e9-3afd13c4f634.ButtonText</value>
      <webElementGuid>714bd614-3074-40ee-8982-7c6b4309ca5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Next&quot;)</value>
      <webElementGuid>db715df9-6aac-46e8-a69f-38c298b69a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>62326dc5-f566-43c9-94a7-77ace4fc3e6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Next']</value>
      <webElementGuid>c02e9888-6fd9-459a-8f1d-109fe2aa4ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField759']/div/input</value>
      <webElementGuid>d7d12cc2-7795-464f-808e-3a27a9a9be82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div[3]/div/div/input</value>
      <webElementGuid>c44b9689-d625-4b8e-82cd-31ea2d856846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Next']</value>
      <webElementGuid>8490f645-74fb-432a-8ee6-83a91d8b0dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
