<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scheme Reference Number_SchemeReferen_a9bf52</name>
   <tag></tag>
   <elementGuidId>ac13fd34-df22-4db8-aed3-1f079d24d484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SchemeReferenceNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SchemeReferenceNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>173f7eaa-8245-435d-90cc-0810625f0955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9b86f23-b7f7-4775-8cd3-45f7b3d4d716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput block field</value>
      <webElementGuid>f023ae97-90d1-45d3-aac1-df2dcccd48c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SchemeReferenceNumber</value>
      <webElementGuid>e2980c07-7e20-498e-8fb9-f21d344ff335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32767</value>
      <webElementGuid>8d5ae87b-b45a-4aef-a7aa-6f40f1903c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SchemeReferenceNumber&quot;)</value>
      <webElementGuid>ae66a8c3-6d1f-443e-8d17-f031e3d28e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>cdbeb957-fcd9-40fc-bca1-044506600e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SchemeReferenceNumber']</value>
      <webElementGuid>53c1da2e-03f2-4b2d-bac2-066b8e6609f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField21']/div/input</value>
      <webElementGuid>d51fe780-7fd9-4ee1-b66a-12f67f9f8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>69c908a1-cb76-4dbd-a684-bc4cff9ec9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SchemeReferenceNumber']</value>
      <webElementGuid>497bdf9f-cae5-425a-8668-860096ad7216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
