<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please SelectInsured PersonEmployerOthers</name>
   <tag></tag>
   <elementGuidId>1c25cb06-becb-47c5-894c-d74a22799666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NoticeandBenefitClaimFormSubmissionby</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NoticeandBenefitClaimFormSubmissionby']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a183c7b-4238-4abf-a5a1-71ab37dd005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field</value>
      <webElementGuid>33c2d098-fd5b-41e0-a252-0dd56e817a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoticeandBenefitClaimFormSubmissionby</value>
      <webElementGuid>6ef12c48-486b-4a52-9d50-ce03c00c66ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabledtoolfn</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f37bbfc-4fc4-4dc7-8a90-8bf445c4915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please SelectInsured PersonEmployerOthers</value>
      <webElementGuid>b5f8cc20-9990-4a67-ba34-e40d80db7bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoticeandBenefitClaimFormSubmissionby&quot;)</value>
      <webElementGuid>01f6b5e1-7c55-43ec-878e-808e6bc4b27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>90607b66-99ea-4954-956e-61b22aadb510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NoticeandBenefitClaimFormSubmissionby']</value>
      <webElementGuid>b653a9e4-8785-4c09-86f3-180c6ece223a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField769']/div/select</value>
      <webElementGuid>d9330191-182a-40e1-b8ad-3c9188357a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>464c58d9-b418-4db8-80ca-5a21f34c7cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice and Benefit Claim Form Submission by'])[1]/following::select[1]</value>
      <webElementGuid>8f2dc0f5-7316-4851-9bcf-5f7c6e613c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClaimFormSubmissionByList'])[1]/preceding::select[1]</value>
      <webElementGuid>3c9637a7-b317-42de-9ba1-5394248b1eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer Code'])[1]/preceding::select[1]</value>
      <webElementGuid>a3cacf2e-9ea9-4d46-b7a5-befa16ab91ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>f58dd586-6cb5-4785-a114-0af53d8d703a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NoticeandBenefitClaimFormSubmissionby' and (text() = 'Please SelectInsured PersonEmployerOthers' or . = 'Please SelectInsured PersonEmployerOthers')]</value>
      <webElementGuid>f99ef3aa-413e-49cf-ae19-c8cdb08983e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
