<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AccidentDeath - PKTDeath - FOTODILAT</name>
   <tag></tag>
   <elementGuidId>3074ece2-4561-4bf2-81a0-eaab065f9c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NoticeTypePreReg']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'NoticeTypePreReg' and (text() = 'AccidentDeath - PKTDeath - FOTODILAT' or . = 'AccidentDeath - PKTDeath - FOTODILAT') and @ref_element = 'Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NoticeTypePreReg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c281aa0-a527-45cc-8f01-d5b779642ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectoption block field</value>
      <webElementGuid>dd0583d4-9c12-41c4-9061-e78e6afabf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoticeTypePreReg</value>
      <webElementGuid>1d7b2b8e-3cc3-4ac8-b525-e08f40137155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AccidentDeath - PKTDeath - FOTODILAT</value>
      <webElementGuid>57fe715a-37ea-4d35-bce0-2bb2d0e13c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoticeTypePreReg&quot;)</value>
      <webElementGuid>d255d58e-bb0b-47c2-a933-a596e80881d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>79affe2f-ffbe-4009-a143-5480dc3b4e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NoticeTypePreReg']</value>
      <webElementGuid>aa87e89e-08ed-440c-b906-156cdffb8a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctrlField596']/div/select</value>
      <webElementGuid>c6f4aece-4ff2-4a55-86ac-ace19f8647e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice Type'])[1]/following::select[1]</value>
      <webElementGuid>98577eb5-dfc2-4ce1-aeb4-ed87ff8d4226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Insured Person &amp; Employer Registration Status'])[1]/following::select[1]</value>
      <webElementGuid>cf5a4067-9261-400f-801d-887bcaae1aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accident Date'])[1]/preceding::select[1]</value>
      <webElementGuid>6d91e8e7-ea6e-42b2-bfd1-680d55cc5e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>034ed54c-621a-4119-85d4-ee4fefcc1823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/select</value>
      <webElementGuid>32d8a173-c71b-403e-82b7-58c15e9e336e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NoticeTypePreReg' and (text() = 'AccidentDeath - PKTDeath - FOTODILAT' or . = 'AccidentDeath - PKTDeath - FOTODILAT')]</value>
      <webElementGuid>16394f08-345b-4450-bfa7-4b8b9a260e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
