<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My Tasks</name>
   <tag></tag>
   <elementGuidId>e8ea80fe-6f04-482f-b090-f2cfbf72c555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lblMyTask</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='lblMyTask']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d406c47f-700f-458e-9572-aad0b85246fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lblMyTask</value>
      <webElementGuid>a2625ce9-45ef-4423-bbcd-7543abc55827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Tasks </value>
      <webElementGuid>e356aac2-0cff-402e-999c-7341b49b0928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblMyTask&quot;)</value>
      <webElementGuid>e1161ee6-ec10-412d-ad82-6d412b7a29b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BARISTA-UAT/iframe_Reemployment Scheduler_baristaPageOut</value>
      <webElementGuid>07528769-6130-4d00-9ac3-903c92dde6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='lblMyTask']</value>
      <webElementGuid>0f83027b-30ef-417d-bed9-dff93b5223ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tab-tasks']/a/span</value>
      <webElementGuid>dc18afbb-6426-4e3d-a8f1-89e365782fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::span[1]</value>
      <webElementGuid>101f457d-d440-4480-84ab-b785882f287b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(38)'])[1]/preceding::span[1]</value>
      <webElementGuid>9a382fcf-d228-4edc-8850-c728911a8bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Queue'])[1]/preceding::span[2]</value>
      <webElementGuid>8b33a64f-a48c-4378-8fcc-978fd070bd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Tasks']/parent::*</value>
      <webElementGuid>c326e1aa-9d35-43f9-ac3e-92dbaa04d5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>cd8b31b2-f088-4a9a-a701-eea03c012c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'lblMyTask' and (text() = 'My Tasks ' or . = 'My Tasks ')]</value>
      <webElementGuid>7fc27aae-3635-4c76-985a-a4cdd4b7de55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
