<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>fccba308-b673-4dca-bf42-b1258abc575a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.primaryAction.signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and (text() = 'Search' or . = 'Search') and @id = 'SearchOb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e374b218-3f46-4023-8b6f-b61c02dbe9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryAction signin-button</value>
      <webElementGuid>eaaf8403-bfe0-4603-9f0f-ed4feadf308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>4b8388bd-3c79-4697-a183-cad4aa9c93a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>3cecb4f7-c274-4f7e-b5be-9f8e44264411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e3ffc205-ca39-45af-967b-199818c89fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d89265a0-87da-40ff-831f-0615570c277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dyn agilepoint-portal-users json no-serviceworker svg supports es6array arrow generators promises filereader fetch localstorage sessionstorage no-getusermedia atobbtoa atob-btoa webworkers contenteditable template placeholder cssgradients pagevisibility requestanimationframe raf bloburls flexbox flexwrap csstransitions compatible datauri blobworkers&quot;]/body[1]/div[@class=&quot;agile-portal sign-page-main&quot;]/div[@class=&quot;agile-portal sign-wrap-main&quot;]/div[@class=&quot;agile-portal sign-contaner-main&quot;]/div[@class=&quot;zone zone-content&quot;]/div[@class=&quot;agile-portal sign-icon-wrap-main inner-sign-contaner-main agile-login&quot;]/div[1]/form[1]/fieldset[@class=&quot;login-form group&quot;]/div[@class=&quot;Signin-btn&quot;]/button[@class=&quot;primaryAction signin-button&quot;]</value>
      <webElementGuid>ddc89f86-8472-403a-8c5c-906586786b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchOb</value>
      <webElementGuid>92b367ba-59f4-4a7b-9f2b-26f20453756c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>40c71e37-b857-47e1-a8dd-359aaa8094e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in'])[1]/following::button[1]</value>
      <webElementGuid>95fdd49c-64d6-47c2-98ac-37e58c421642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>487468ed-48c0-41d9-83a6-b8431ec452ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© AgilePoint, Inc. 2024 All rights reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>ede33d52-6663-450b-86b2-d3f21c4075af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>3c3ed627-8088-45bb-8a56-2638432e906b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>86a6499e-7a46-46a3-a105-b79c242df939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sign In' and @type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>01087de8-de63-498e-a482-a957991d9b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
