<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>53905317-27ae-4a4d-b990-45d8443dd056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.primaryAction.signin-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5adfb6ee-621c-44c8-aafe-ea148f39efca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryAction signin-button</value>
      <webElementGuid>b9d74504-02d9-4902-bc0c-c54878a11f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>484e0157-7c61-43ec-9399-67721563c780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>28d8a0f3-90e8-4bed-a3ba-4d38fb082b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fdd56b44-b70e-4525-92d7-7edc1d04e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>298b5696-9d6b-4adc-a061-b783ae8900e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dyn agilepoint-portal-users json no-serviceworker svg supports es6array arrow generators promises filereader fetch localstorage sessionstorage no-getusermedia atobbtoa atob-btoa webworkers contenteditable template placeholder cssgradients pagevisibility requestanimationframe raf bloburls flexbox flexwrap csstransitions compatible datauri blobworkers&quot;]/body[1]/div[@class=&quot;agile-portal sign-page-main&quot;]/div[@class=&quot;agile-portal sign-wrap-main&quot;]/div[@class=&quot;agile-portal sign-contaner-main&quot;]/div[@class=&quot;zone zone-content&quot;]/div[@class=&quot;agile-portal sign-icon-wrap-main inner-sign-contaner-main agile-login&quot;]/div[1]/form[1]/fieldset[@class=&quot;login-form group&quot;]/div[@class=&quot;Signin-btn&quot;]/button[@class=&quot;primaryAction signin-button&quot;]</value>
      <webElementGuid>92e263ba-0c57-4896-b549-eee90e414fff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>f67b3675-9df4-4b3c-a5b8-0342d702530a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keep me signed in'])[1]/following::button[1]</value>
      <webElementGuid>cab2269e-6a09-429f-a233-2dc78bc4e75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>3afe55b0-8b91-493d-a136-1599737d18c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© AgilePoint, Inc. 2024 All rights reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>bb9ddeb6-dd5f-40e7-a6d1-52f9060b464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign In']/parent::*</value>
      <webElementGuid>34dfade6-dfb0-4538-87a2-feab83202f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f4749f65-3585-413f-a355-25933c8e2275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sign In' and @type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>987b5d0e-700e-46c7-83a7-758ba6d89072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
