<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_userNameOrEmail</name>
   <tag></tag>
   <elementGuidId>43b02b95-874e-428f-a4b0-90bac4d00056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87a6523d-41cc-42d9-a482-6a67ee8cb288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>username-text-box</value>
      <webElementGuid>cab88329-576b-495b-815c-c7dea18fb962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username-email</value>
      <webElementGuid>dd1ef5cd-3f2f-4330-8dba-2043f496005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userNameOrEmail</value>
      <webElementGuid>ed1224bb-c3c4-4bc0-b455-dcd36fb30ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>b9226142-aadd-45f8-a80b-08673f1b490e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>00feb072-9c5b-408c-98ee-9289e2db11c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74bd713a-5ac1-4bf3-ad37-fe285a6254a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username-email&quot;)</value>
      <webElementGuid>78f4046c-8502-4b17-8cd2-72e22edfe70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username-email']</value>
      <webElementGuid>5125a99e-73d4-4c5d-8f23-4e8e3de40bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>05c6e3e1-1e61-4f90-b8a4-90f5172a4f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'username-email' and @name = 'userNameOrEmail' and @placeholder = 'User Name' and @type = 'text']</value>
      <webElementGuid>01af0d47-efe3-494f-b077-2fccec8963fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
