<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pre-Registration</name>
   <tag></tag>
   <elementGuidId>490b84fb-8b8f-4662-957c-96d1f8c48b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ap-MenuItem-Content.ap-MenuItemContent--TopLevel.ap-MenuItemContent--Hover.content-54 > a.ap-MenuItem-link.link-49</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@target = '_self' and (text() = 'Pre-Registration' or . = 'Pre-Registration')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-builder-root']/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6fa057d-f01b-44cc-852c-15b777ab16a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-MenuItem-link link-49</value>
      <webElementGuid>5821011d-5a2d-4183-95d2-5be224b32df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pages/barista?v=prereg</value>
      <webElementGuid>d6b0b7d2-cb3d-4650-bc9f-3fdca187b3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>8d629c56-d554-4755-a0f0-f9eb4505cce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pre-Registration</value>
      <webElementGuid>b5c70b14-6eee-44ac-bac1-ab82cc021193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-builder-root&quot;)/div[@class=&quot;ms-Fabric appContainer_ee6f111b root-41&quot;]/div[@class=&quot;runtimeLayout-42&quot;]/div[@class=&quot;ap-Pages-runtimeLayoutContent ap-Pages-pageBackground ap-Pages-pageLayout runtimeLayoutContent-43&quot;]/div[@class=&quot;root-44 pageBuilderSurface&quot;]/div[@class=&quot;pageSection_d6bb0522 pageControl section- full-height&quot;]/div[@class=&quot;controlsContainer controlsContainer_d6bb0522&quot;]/div[@class=&quot;ms-Grid-col ms-sm12 ms-style ms-className sectionColumn_c1b50373 pageControl customizedDimension_c1b50373&quot;]/div[@class=&quot;controlsContainer controlsContainer_d6bb0522 controlsContainer_c1b50373&quot;]/div[@class=&quot;ap-Menu-Wrapper ap-Menu-BgImage ap-Menu-SubMenu-BgImage ap-Menu-SubMenu-Bg root-45&quot;]/div[@class=&quot;ap-Menu rootContentFlex-46&quot;]/div[@class=&quot;ap-Menu-Items rootContent-47&quot;]/div[@class=&quot;ap-MenuItem root-48&quot;]/div[@class=&quot;ap-MenuItem-Content ap-MenuItemContent--TopLevel ap-MenuItemContent--Hover content-54&quot;]/a[@class=&quot;ap-MenuItem-link link-49&quot;]</value>
      <webElementGuid>512a8c92-d007-49f9-83a2-03845691765f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-builder-root']/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>cdaa8773-154c-4d37-92f6-98f20c78c365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pre-Registration')]</value>
      <webElementGuid>50104396-bac9-4f77-84e0-6dc95e73d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[1]</value>
      <webElementGuid>6d696866-fdeb-4466-940b-ca02f89480ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BARISTA Main'])[1]/following::a[2]</value>
      <webElementGuid>4b40e0f1-46e2-4c0e-8088-0c50e5ffdea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUK Pre-Registration'])[1]/preceding::a[1]</value>
      <webElementGuid>147066af-1247-4c06-adf3-6974b36489b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Revision'])[1]/preceding::a[2]</value>
      <webElementGuid>be8f06fc-8543-448f-8337-16089670f738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pre-Registration']/parent::*</value>
      <webElementGuid>613c8f68-74fe-429c-a14a-5da20699cc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pages/barista?v=prereg')]</value>
      <webElementGuid>636bf797-7f28-43ba-9acd-a233145cff9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a</value>
      <webElementGuid>0eafe1bf-e613-4750-b305-121ceaa68b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pages/barista?v=prereg' and (text() = 'Pre-Registration' or . = 'Pre-Registration')]</value>
      <webElementGuid>1c717344-e899-460a-b3ff-71d3e2072087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
